theme: jekyll-theme-minimal
source: .
destination: _site
exclude:
- Gemfile
- Gemfile.lock
keep_files:
- _data/
collections:
    projects:
        name: projects
        output: true
        permalink: "/projects/:path"
