theme: jekyll-theme-minimal
source: .
destination: _site
exclude:
- Gemfile
- Gemfile.lock
- nginx.conf
collections:
    projects:
        name: projects
        output: true
        permalink: "/projects/:path"
